project_id = "pqzznpnbtlgmrlsmdhkv"

[functions.create-installment-plan]
verify_jwt = false

[functions.process-scheduled-payments]
verify_jwt = false

[functions.trigger-payment-now]
verify_jwt = false

[functions.cancel-booking]
verify_jwt = false