// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqzznpnbtlgmrlsmdhkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxenpucG5idGxnbXJsc21kaGt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDM0NDksImV4cCI6MjA3NDM3OTQ0OX0.pWRnfEwJ0FhZhLU9JNQ1q5zYRJ3o8bx0Ij0tO_udlt0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});